spring:
  profiles: cloud
  jpa:
    generate-ddl: true
    show-sql: true
server: 
  port: 0
security:
  oauth2:
    resource:
      user-info-uri: http://trapps-api.local.pcfdev.io/user
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trappsdb?useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles: local
  devtools:
    restart:
      enabled: true
server: 
  port: 8081
security:
  basic:
    enabled: false
logging:
  level:
    org.spring.security: DEBUG
    org.springframework.web: ERROR
    com.insys.trapps: DEBUG
    org.hibernate: ERROR
authentication:
  oauth:
    clientid: trapps-app
    secret: QQsfDh5Q7S1BB8UHiB0Ni3okKn8lEEbeDx1k4k2OjT2jWuzr
    tokenValidityInSeconds: 1800
---
spring:
  profiles: local,cloud
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    rest:
      basePath: /api/v1
      defaultMediaType: application/json
---
security:
  basic:
    enabled: false