spring:
  jpa:
    generate-ddl: true
    show-sql: true
    database: H2
  data:
    rest:
      basePath: /api
  h2:
     console:
       enabled: true
       path: /console 
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2