spring:
  profiles: cloud
server: 
  port: 0
security:
  oauth2:
    resource:
      user-info-uri: http://trapps-api.local.pcfdev.io/user
logging:
  level:
    org.spring.security: TRACE
    org.springframework.web: TRACE
    com.insys.trapps: TRACE
    org.hibernate: TRACE
aws:
  s3:
    endpoint: s3.amazonaws.com
    credentials:
      accessKey: AKIAJQNOIHWF4AREOMVA
      secretKey: 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
---
spring:
  profiles: local
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/trappsdb?useSSL=false
    username: root
    password: root
  devtools:
    restart:
      enabled: true
server: 
  port: 8081
security:
  basic:
    enabled: false
logging:
  level:
    org.spring.security: INFO
    org.springframework.web: INFO
    com.insys.trapps: INFO
    org.hibernate: INFO
aws:
  s3:
    endpoint: http://127.0.0.1:9000
    credentials:
      accessKey: F1O0TGTIO8S3OCJTQPKK
      secretKey: 6rErai/xOd8sO43eJ+8GxEJi73ct6Q/jYiOe85fH
---
spring:
  profiles: local,cloud
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    rest:
      basePath: /api/v1
      defaultMediaType: application/json
  mail:
    cc: areyna@luxoft.com
    username: trapps.donotreply@gmail.com
    password: Tr4pps#2017
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        transport:
          protocol: smpt
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
authentication:
  oauth:
    clientid: trapps-app
    secret: QQsfDh5Q7S1BB8UHiB0Ni3okKn8lEEbeDx1k4k2OjT2jWuzr
    tokenValidityInSeconds: 6000
aws:
  s3:
    buckets:
      person: persondocument
multipart.maxFileSize: 5MB
multipart.maxRequestSize: 5MB
---
security:
  basic:
    enabled: false