spring:
  profiles: cloud
  jpa:
    generate-ddl: true
    show-sql: true
server: 
  port: 0
security:
  oauth2:
    resource:
      user-info-uri: http://trapps-api.local.pcfdev.io/user
trapps:
  access-token:
    url: http://trapps-api.local.pcfdev.io/oauth/token
  client:
    apps: http://trapps-web.local.pcfdev.io
---
spring:
  profiles: local
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          import_files: local_insert.sql
  h2:
    console:
      enabled: true
      path: /console
server: 
  port: 8081
security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://NJ395MAC11.fios-router.home:8081/user
trapps:
  access-token:
    url: http://NJ395MAC11.fios-router.home:8081/oauth/token
  client:
    apps: http://localhost:4201
logging:
  level:
    org.spring.security: DEBUG
    org.springframework.web: DEBUG
    com.insys.trapps: DEBUG
    org.hibernate: ERROR
---
spring:
  profiles: local,cloud
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    rest:
      basePath: /api/v1
      defaultMediaType: application/json
---
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: trapps-application
      client-secret: trapps-application-secret
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials
      scope: read,write
      
  