---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  HEALTH_URL:

inputs:
- name: trapps-api-source

run:
  path: trapps-api-source/ci/tasks/smoke-test.sh
