---
resources:
- name: trapps-api-source
  type: git
  source:
    uri: https://github.com/insys-group/trapps-api.git
    branch: feature/concourse
- name: deploy-trapps-api
  type: cf
  source:
    api: api.system.luxoft-pcf.com
    username: concourse
    password:
    organization: insys
    space: development
    skip_cert_check: true
- name: release
  type: s3
  source:
    bucket: pcf-stack2-concoursetrappsbucket
    regexp: trapps-api/trapps-(*).jar
    access_key_id: AKIAIS3Y4EOKVNIAE7OQ
    secret_access_key: 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

jobs:
- name: build
  public: true
  plan:
  - get: trapps-api-source
    trigger: true
  - task: package
    file: trapps-api-source/ci/tasks/package.yml
  - put: release
    params:
      file: package-output/trapps-api.jar
  
- name: deploy
  public: true
  plan:
  - get: trapps-api-source
    trigger: false
    passed: [build]
  - put: deploy-trapps-api
    params:
      manifest: trapps-api-source/manifest.yml
      path: s3://trapps-api/trapps-api.jar

- name: smoke_test
  public: true
  plan:
  - get: trapps-api-source
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: trapps-api-source/ci/tasks/smoke-test.yml
    params:
      HEALTH_URL: http://trapps-api.local.pcfdev.io/health
